Workflow:
  '@WorkflowId': '{f0b55173-7ba7-f011-bbd2-000d3a9a284c}'
  '@Name': get flows
  JsonFileName: /modernflows/f0b55173-7ba7-f011-bbd2-000d3a9a284c/getflows-F0B55173-7BA7-F011-BBD2-000D3A9A284C.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': get flows
