Workflow:
  '@WorkflowId': '{749435dc-9c65-f011-bec2-7c1e5219079a}'
  '@Name': Translate
  JsonFileName: /modernflows/749435dc-9c65-f011-bec2-7c1e5219079a/Translate-749435DC-9C65-F011-BEC2-7C1E5219079A.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Translate
