Workflow:
  '@WorkflowId': '{0befd648-eea5-f011-bbd2-7c1e52804440}'
  '@Name': ExpandQuery
  JsonFileName: /modernflows/0befd648-eea5-f011-bbd2-7c1e52804440/ExpandQuery-0BEFD648-EEA5-F011-BBD2-7C1E52804440.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': ExpandQuery
