environmentvariabledefinition:
  '@schemaname': cr7d6_postlink
  defaultvalue: postlink
  displayname:
    '@default': postlink
    label:
      '@description': postlink
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
