Workflow:
  '@WorkflowId': '{76147395-3fa4-f011-bbd2-7ced8d21ddf3}'
  '@Name': Update Array
  JsonFileName: /modernflows/76147395-3fa4-f011-bbd2-7ced8d21ddf3/UpdateArray-76147395-3FA4-F011-BBD2-7CED8D21DDF3.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': Update Array
