Workflow:
  '@WorkflowId': '{6e543d09-8fa7-f011-bbd2-000d3a9a284c}'
  '@Name': FlowCallbackurls
  JsonFileName: /modernflows/6e543d09-8fa7-f011-bbd2-000d3a9a284c/FlowCallbackurls-6E543D09-8FA7-F011-BBD2-000D3A9A284C.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': FlowCallbackurls
