Workflow:
  '@WorkflowId': '{9b7b8967-385f-f011-bec2-7c1e5219079a}'
  '@Name': PA12
  JsonFileName: /modernflows/9b7b8967-385f-f011-bec2-7c1e5219079a/PA12-9B7B8967-385F-F011-BEC2-7C1E5219079A.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': PA12
